config/routes.rb
Rails.application.routes.draw do
  
  post 'add_to_cart' => 'cart#add_to_cart'

  get 'view_order' => 'cart#view_order'

  get 'checkout' => 'cart#checkout'

  get 'delete_line_item' => 'cart#delete_line_item'

  post 'edit_line_item' => 'cart#edit_line_item'

  post 'order_complete' => 'cart#order_complete'

  devise_for :users

  root 'storefront#all_items'

  get 'categorial' => 'storefront#items_by_category'

  get 'branding' => 'storefront#items_by_brand'

  resources :products

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end

    if user.admin?
        can :manage, Product
    end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :products
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
	belongs_to :product
	belongs_to :order
end

app/models/order.rb
class Order < ActiveRecord::Base
	has_many :line_items
	belongs_to :user

	serialize :order_items, Hash
end

app/models/product.rb
class Product < ActiveRecord::Base
	mount_uploader :image, ImageUploader
	belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :orders

  def admin?
  	role == "admin"
  end

  def guest?
  	role == "guest"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :categories, :brands

  def categories
  	@categories = Category.order(:name)
  end

  def brands
  	@brands = Product.pluck(:brand).uniq!
  end

  before_action :configure_permitted_parameters, if: :devise_controller?

  helper_method :current_order

  def current_order
    if !session[:order_id].nil?
      Order.find(session[:order_id])
    else
      Order.new
    end
  end

  protected

  def configure_permitted_parameters

    devise_parameter_sanitizer.permit(:sign_up, keys: [:role, :name])

    devise_parameter_sanitizer.permit(:account_update, keys: [:role, :name])
  end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController

	before_filter :authenticate_user!, except: [:add_to_cart, :view_order]


  def add_to_cart
  	product = Product.find(params[:product_id])
  	if params[:quantity].to_i > product.quantity
  		redirect_to product, notice: "Only #{product.quantity} left in stock! Please revise order."
  	else

      @order = current_order

	  	line_item = @order.line_items.new(product_id: params[:product_id], quantity: params[:quantity])
      @order.save
      session[:order_id] = @order.id

	  	line_item.line_item_total = Product.find(params[:product_id]).price * line_item.quantity
	  
	  	line_item.save

	  	redirect_to :back
	  end
  end

  def view_order
  	@line_items = current_order.line_items
  end

  def checkout
  	line_items = current_order.line_items
  	current_order.update(user_id: current_user.id, subtotal: 0)

    @order = current_order

  	line_items.each do |line_item|
  		@order.subtotal += line_item.line_item_total
  		@order.order_items[line_item.product_id] = line_item.quantity
  	end

  	@order.sales_tax = @order.subtotal * 0.07
  	@order.grand_total = @order.subtotal + @order.sales_tax
  	@order.save

  	line_items.each do |line_item|
  		line_item.product.quantity -= line_item.quantity
  		line_item.product.save
  	end

  	@order.line_items.destroy_all

  end

  def delete_line_item
    LineItem.find(params[:id]).destroy
    redirect_to :back
  end

  def edit_line_item
    x = LineItem.find(params[:id])

    @notice = nil

    if params[:quantity].to_i < x.product.quantity
      x.update(quantity: params[:quantity])
    else
      @notice = "Only #{x.product.quantity} left in stock! Unable to revise order."
    end

    redirect_to :back, notice: @notice
  end

  def order_complete
    @order = Order.find(params[:order_id])
    @amount = (@order.grand_total.to_f.round(2) * 100).to_i

    customer = Stripe::Customer.create(
      :email => current_user.email,
      :card => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer => customer.id,
      :amount => @amount,
      :description => 'Rails Stripe customer',
      :currency => 'usd'
    )

    rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to charges_path
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  before_filter :authenticate_user!, except: [:show]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :price, :quantity, :description, :brand, :rating, :category_id, :image)
    end
end

app/controllers/storefront_controller.rb
class StorefrontController < ApplicationController
  def all_items
  	@products = Product.all
  end

  def items_by_category
  	@products = Product.where(category_id: params[:cat_id])
  	@category = Category.find(params[:cat_id]).name
  end

  def items_by_brand
  	@brand = params[:brand]
  	@products = Product.where(brand: params[:brand])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/storefront_helper.rb
module StorefrontHelper
end

app/views/cart/checkout.html.erb
<h2>Thanks for shopping with us!</h2>
<p>Let's review your order:</p>

<% @order.order_items.each do |k,v| %>
	<ul>
		<li><%= Product.find(k).name %></li>
		<li>Qty. purchased: <%= v %></li>
	</ul>
<% end %>

<p>
	<strong>Subtotal:</strong> <%= number_to_currency @order.subtotal %>
</p>

<p>
	<strong>Sales Tax:</strong> <%= number_to_currency @order.sales_tax %>
</p>

<p>
	<strong>Order Total:</strong> <%= number_to_currency @order.grand_total %>
</p>

<div>
	<%= form_tag order_complete_path do %>
		<article>
			<label class="amount">
				<span><%= number_to_currency @order.grand_total %></span>
			</label>
		</article>

		<%= hidden_field_tag :order_id, @order.id %>

		<script src="http://checkout.stripe.com/checkout.js"
		class="stripe-button"
		data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
		data-description="Order #<%= @order.id %>"
		data-amount="<%= (@order.grand_total.to_f.round(2) * 100) %>"></script>

	<% end %>
</div>

app/views/cart/order_complete.html.erb
<h2>Thank you for your order!</h2>

<h4>
	Order #<%= @order.id %> will be shipping to you, <%= @order.user.name %>,
	as soon as possible!
</h4>

app/views/cart/view_order.html.erb
<h2>My Cart</h2>

<div>
	<% @line_items.each_with_index do |line_item, index| %>
		<ul>
			<li><%= line_item.product.name %></li>
			<li><%= number_to_currency line_item.product.price %></li>
			<span id="notice"><%= notice %></span>
			<li id="quantity<%= index %>">Qty: <%= line_item.quantity %> <a id="edit<%= index %>">Edit</a></li>
			<span id="edit_form<%= index %>" class="invisible">
				<%= form_tag edit_line_item_path do %>
					<%= hidden_field_tag :id, line_item.id %>
					<%= number_field_tag :quantity, line_item.quantity %>
					<%= submit_tag "Change Quantity", class: "btn btn-warning" %>
				<% end %>
			</span>
			<li>Subtotal: <%= number_to_currency line_item.line_item_total %></li>
		</ul>
		<%= link_to "Delete", delete_line_item_path(id: line_item.id) %>


		<script>
			$(document).ready(function(){
				$("#edit<%= index %>").click(function(){
					$("#quantity<%= index %>").addClass("invisible");
					$("#edit_form<%= index %>").removeClass("invisible");
				})
			})
		</script>
	<% end %>
</div>

<div>
	<%= link_to "Proceed to Checkout?", checkout_path, class: "btn btn-success" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>eCommerce App</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<nav class="navbar navbar-default">
	  <div class="container-fluid">
	    <!-- Brand and toggle get grouped for better mobile display -->
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	      <%= link_to "Home", root_path, class: "navbar-brand" %>
	    </div>

	    <!-- Collect the nav links, forms, and other content for toggling -->
	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	      <ul class="nav navbar-nav">
	        <li class="dropdown">
	          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories <span class="caret"></span></a>
	          <ul class="dropdown-menu">
	          	<% @categories.each do |cat| %>
		            <li>
		            	<%= link_to cat.name, categorial_path(cat_id: cat.id) %>
		            </li>
		           <% end %>
	          </ul>
	        </li>
	        <li class="dropdown">
	          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Brands <span class="caret"></span></a>
	          <ul class="dropdown-menu">
	          	<% @brands.each do |brand| %>
		            <li>
		            	<%= link_to brand, branding_path(brand: brand) %>
		            </li>
		           <% end %>
	          </ul>
	        </li>
	      </ul>
	      <form class="navbar-form navbar-left">
	        <div class="form-group">
	          <input type="text" class="form-control" placeholder="Search">
	        </div>
	        <button type="submit" class="btn btn-default">Submit</button>
	      </form>
	      <ul class="nav navbar-nav navbar-right">
	       	<li><%= link_to "View Cart", view_order_path %></li>
	        <% if user_signed_in? %>
		        <li class="dropdown">
		          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Hello, <%= current_user.name %> <span class="caret"></span></a>
		          <ul class="dropdown-menu">
		            <li><a href="#">View Previous Orders</a></li>
		            <li>
		            	<%= link_to "Edit Profile", edit_user_registration_path %>
		            </li>
		            <li>
									<%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
								</li>
		          </ul>
		        </li>
		      <% else %>
		      	<li>
		      		<li>
		      			<%= link_to "Sign In", new_session_path(:user) %>
		      		</li>
		      		<li>
		      			<%= link_to "Sign Up", new_registration_path(:user)  %>
		      		</li>
		      	</li>
		      <% end %>
	      </ul>
	    </div><!-- /.navbar-collapse -->
	  </div><!-- /.container-fluid -->
	</nav>

	<div class="container">
		<%= yield %>
	</div>

</body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.text_field :name, placeholder: "Product Name", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.text_field :price, placeholder: "Price", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.number_field :quantity, placeholder: "Quantity In Stock", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.text_area :description, placeholder: "Product Description", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.text_field :brand, placeholder: "Brand Name", class: "form-control" %>
  </div>
  <!-- <div class="field"> -->
    <%#= f.label :rating %><!-- <br> -->
    <%#= f.number_field :rating %>
  <!-- </div> -->
  <div class="form-group">
    <%= f.select :category_id, @categories.collect {|c| [c.name, c.id]}, { include_blank: "Please Select a Category"}, class: "form-control" %>
  </div>
  <div class="form-group">
    <strong>Upload Product Image: </strong>
    <%= f.file_field :image %>
  </div>

  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/products/edit.html.erb
<% if can? :manage, Product %>

	<div class="row">
	  <div class="col-md-8 col-md-offset-2">
			<h1>Update Product Details</h1>

			<%= render 'form' %>

			<%= link_to 'Show', @product %> |
			<%= link_to 'Back', products_path %>
		</div>
	</div>
	
<% end %>

app/views/products/index.html.erb
<% if can? :manage, Product %>
  <h1>Listing Products</h1>

  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Price</th>
        <th>Quantity</th>
        <th>Description</th>
        <th>Brand</th>
        <th>Rating</th>
        <th>Category</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @products.each do |product| %>
        <tr>
          <td><%= product.name %></td>
          <td><%= number_to_currency product.price %></td>
          <td><%= product.quantity %></td>
          <td><%= product.description %></td>
          <td><%= product.brand %></td>
          <td>n/a<%#= product.rating %></td>
          <td><%= product.category.name %></td>
          <td><%= link_to 'Show', product %></td>
          <td><%= link_to 'Edit', edit_product_path(product) if can? :update, product %></td>
          <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } if can? :destroy, product %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <% if can? :create, Product %>
    <%= link_to 'New Product', new_product_path %>
  <% end %>
<% end %>

app/views/products/new.html.erb
<% if can? :manage, Product %>

	<div class="row">
	  <div class="col-md-8 col-md-offset-2">
			<h1>Enter New Product Details</h1>

			<%= render 'form' %>

			<%= link_to 'Back', products_path %>
		</div>
	</div>

<% end %>

app/views/products/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @product.quantity %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Brand:</strong>
  <%= @product.brand %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @product.rating %>
</p>

<p>
  <strong>Category:</strong>
  <%= @product.category.name %>
</p>

<% if (user_signed_in?) && (can? :manage, Product) %>
  <%= link_to 'Edit', edit_product_path(@product) %> |
  <%= link_to 'Back', products_path %>
<% end %>

<p id="notice"><%= notice %></p>
<% if @product.quantity > 0 %>
  <p>
    <%= form_tag add_to_cart_path do %>
      <%= hidden_field_tag :product_id, @product.id %>
      <%= number_field_tag :quantity, nil, placeholder: "How Many?" %>
      <%= submit_tag "Add to Cart", class: "btn btn-primary" %>
    <% end %>
  </p>
<% end %>

app/views/storefront/_productloop.html.erb
<div class="row">
	<% @products.each do |product| %>
		<div class="col-md-4">
			<div class="well center-it">
				<p><%= image_tag product.image.url, width: "100" %></p>
				<p><%= link_to product.name, product %></p>
				<p><%= number_to_currency product.price %></p>
				<p>
					<a href="#" data-toggle="modal" data-target="#myModal_<%= product.id %>">
						<i class="glyphicon glyphicon-plus"></i> Quick Info
					</a>
				</p>
			</div>
		</div>
		<div class="modal fade" id="myModal_<%= product.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
		  <div class="modal-dialog" role="document">
		    <div class="modal-content">
		      <div class="modal-header">
		        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		        <h4 class="modal-title" id="myModalLabel"><%= product.name %></h4>
		      </div>
		      <div class="modal-body">
		        <p><%= number_to_currency product.price%></p>
		        <p>made by <%= product.brand %></p>
		        <p><%= product.description %></p>
		      </div>
		      <div class="modal-footer">
		        <p>
		        	<% if product.quantity > 0 %>
			        	<%= form_tag add_to_cart_path do %>
			        		<%= hidden_field_tag :product_id, product.id %>
			        		<%= number_field_tag :quantity, nil, placeholder: "How Many?" %>
			        		<%= submit_tag "Add to Cart", class: "btn btn-primary" %>
			        	<% end %>
			        <% else %>
			        	SOLD OUT!
			        <% end %>
		        </p>
		      </div>
		    </div>
		  </div>
		</div>
	<% end %>
</div>

app/views/storefront/all_items.html.erb
<h1>Welcome to BuyIt!</h1>
<p>Give us your money!</p>

<%= render 'productloop' %>

app/views/storefront/items_by_brand.html.erb
<h1>All of Our Products by <%= @brand %></h1>

<%= render 'productloop' %>

app/views/storefront/items_by_category.html.erb
<h1>All of Our <%= @category %> Products</h1>

<%= render 'productloop' %>